name: Blog Frontend CI
on:
  push:
    branches:
      - main
  pull-request:
    bracnhes:
      - main
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]